server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forest-dashboard?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
